# -*- coding: utf-8 -*-
"""TareaConcurso2Plantas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kiQQvsiZDegNibPflqhTHOcKhXSbSUSD

INSTALAMOS LO NECESARIO
"""

!pip install mlflow
!pip install optuna
!pip install scikit-learn

import os
from getpass import getpass
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import mlflow
import mlflow.keras
import tensorflow as tf
from tensorflow.keras import layers, models, callbacks, optimizers, regularizers
from tensorflow.keras.applications import EfficientNetB2
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, Callback, ReduceLROnPlateau
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
import optuna
import json
import time
import shutil
print("La librerias fueron importadas correctamente")

"""DAGSHUB Y MLFLOW"""

REPO_OWNER = "javimesa16"
REPO_NAME = "ConcursoPlantas"
USER_NAME = "javimesa16"

if REPO_OWNER and REPO_NAME:
    tracking_uri = f'https://dagshub.com/{REPO_OWNER}/{REPO_NAME}.mlflow'
    print("Usando MLflow tracking URI:", tracking_uri)
    os.environ['MLFLOW_TRACKING_USERNAME'] = USER_NAME
    os.environ['MLFLOW_TRACKING_PASSWORD'] = getpass('Enter your DAGsHub access token or password: ')
    mlflow.set_tracking_uri(tracking_uri)
else:
    print("No se proporcionó REPO_OWNER/REPO_NAME. Usando MLflow local (archivo).")

"""CONFIGURAMOS EL EXPERIMENTO DE OPTUNA"""

EXPERIMENT_NAME = "PlantPathology_Optuna_Categorical_FIXED_v2"
N_TRIALS = 20
FINAL_EPOCHS = 50 #nota al final en mi tarea solo llego a 20 epocas debido  a que no mejoro
BATCH_SIZE = 32
IMG_SIZE = (256, 256)

"""CONECTAMOS A DRIVE"""

#hacemos la coneccion a google drive
print("conectando a Google Drive...")
from google.colab import drive
drive.mount('/content/drive')

# ruta
DRIVE_BASE_PATH = "/content/drive/MyDrive/Concurso/PlantPathology/"
IMAGES_PATH = os.path.join(DRIVE_BASE_PATH, "images/")
TRAIN_CSV_PATH = os.path.join(DRIVE_BASE_PATH, "train.csv")

print(f" Rutas configuradas:")
print(f"   - Imágenes: {IMAGES_PATH}")
print(f"   - Train CSV: {TRAIN_CSV_PATH}")

"""CARGA DE DATOS"""

#cargamos los datos que vamos a usar
def cargar_datos_y_crear_estructura():

    # cargamos train.csv
    print(" Cargando train.csv...")
    if not os.path.exists(TRAIN_CSV_PATH):
        print(f"ERROR: No se encuentra {TRAIN_CSV_PATH}")
        return None, None, None, 0, 0

    train_df = pd.read_csv(TRAIN_CSV_PATH)

    # verificamos la estructura
    clases = ['healthy', 'multiple_diseases', 'rust', 'scab']
    print(" Distribución de clases:")
    for clase in clases:
        count = train_df[clase].sum()
        print(f"   {clase}: {count} imágenes ({count/len(train_df)*100:.1f}%)")

    # la divicion de datos sera (70% train, 30% test)
    print("\n Dividiendo datos...")
    train_data, test_data = train_test_split(
        train_df,
        test_size=0.3,
        random_state=42,
        stratify=train_df[clases].values.argmax(axis=1)
    )

    print(f" Datos de entrenamiento: {len(train_data)} imágenes")
    print(f" Datos de test: {len(test_data)} imágenes")

    # se crea la estructura de directorios
    print("\n Creando estructura de directorios...")
    base_temp_path = "/content/plant_pathology_structured"

    # se limpia el directorio temporal si existe
    if os.path.exists(base_temp_path):
        shutil.rmtree(base_temp_path)

    # creamos los directorios
    train_dir = os.path.join(base_temp_path, "train")
    test_dir = os.path.join(base_temp_path, "test")

    os.makedirs(train_dir, exist_ok=True)
    os.makedirs(test_dir, exist_ok=True)

    # hacemos los mismo con los subdirectorios
    for clase in clases:
        os.makedirs(os.path.join(train_dir, clase), exist_ok=True)
        os.makedirs(os.path.join(test_dir, clase), exist_ok=True)

    # esta funcion es para copiar las images
    def copiar_imagenes(dataframe, target_dir, dataset_type):
        copied_count = 0
        for idx, row in dataframe.iterrows():
            image_id = row['image_id']
            source_path = os.path.join(IMAGES_PATH, f"{image_id}.jpg")

            # se determina la clase
            for clase in clases:
                if row[clase] == 1:
                    target_path = os.path.join(target_dir, clase, f"{image_id}.jpg")
                    if os.path.exists(source_path):
                        shutil.copy2(source_path, target_path)
                        copied_count += 1
                    break

        print(f"   - {dataset_type}: {copied_count} imágenes copiadas")
        return copied_count

    # copiamos las imagenes
    print(" Copiando imágenes de entrenamiento...")
    train_count = copiar_imagenes(train_data, train_dir, "Train")

    print(" Copiando imágenes de test...")
    test_count = copiar_imagenes(test_data, test_dir, "Test")

    print(f" Estructura creada: {train_count + test_count} imágenes totales")

    return train_dir, test_dir, clases, len(train_data), len(test_data)

# se crea la estructura
train_dir, test_dir, clases, train_count, test_count = cargar_datos_y_crear_estructura()
num_classes = len(clases)

"""GENERADORES"""

#creamos los generadores
def crear_generadores_finales(train_dir, test_dir, img_size=(256, 256), batch_size=32):


    print(" Creando generadores con flow_from_directory...")
#usamos estos rangos
    train_datagen = ImageDataGenerator(
        rotation_range=20,
        width_shift_range=0.2,
        height_shift_range=0.2,
        horizontal_flip=True,
        zoom_range=0.2,
        brightness_range=[0.8, 1.2],
        validation_split=0.2
    )

    test_datagen = ImageDataGenerator()

    train_generator = train_datagen.flow_from_directory(
        train_dir,
        target_size=img_size,
        batch_size=batch_size,
        class_mode='categorical',
        subset='training',
        shuffle=True
    )

    val_generator = train_datagen.flow_from_directory(
        train_dir,
        target_size=img_size,
        batch_size=batch_size,
        class_mode='categorical',
        subset='validation',
        shuffle=False
    )

    test_generator = test_datagen.flow_from_directory(
        test_dir,
        target_size=img_size,
        batch_size=batch_size,
        class_mode='categorical',
        shuffle=False
    )
    print(" Generadores creados CORRECTAMENTE")
    print(f"   - Training: {train_generator.samples} imágenes")
    print(f"   - Validation: {val_generator.samples} imágenes")
    print(f"   - Test: {test_generator.samples} imágenes")
    print(f"   - Clases: {train_generator.class_indices}")

    return train_generator, val_generator, test_generator

# los creamos los finales
print("\n Creando generadores finales...")
train_gen, val_gen, test_gen = crear_generadores_finales(train_dir, test_dir, IMG_SIZE, BATCH_SIZE)

"""SUBIMOS LAS GRAFICAS

"""

#debido a que implementamos un cambio en el learning rate
#tambien lo graficamos para ver como cambia
class MLflowEpochLogger(Callback):
    def __init__(self, run_id=None, log_every_n_epochs=1, plot_every_n_epochs=5):
        super().__init__()
        self.log_every_n_epochs = log_every_n_epochs
        self.plot_every_n_epochs = plot_every_n_epochs
        self.history = {
            'loss': [], 'val_loss': [], 'accuracy': [], 'val_accuracy': []
        }
        self.run_id = run_id

    def on_epoch_end(self, epoch, logs=None):
        logs = logs or {}

        # se actualiza el historial (solo train y val)
        for k in ['loss', 'val_loss', 'accuracy', 'val_accuracy']:
            if k in logs:
                self.history[k].append(float(logs[k]))

        # registramos las metricas
        if (epoch + 1) % self.log_every_n_epochs == 0:
            for k, v in logs.items():
                try:
                    mlflow.log_metric(k, float(v), step=epoch)
                except Exception as e:
                    print("Warning mlflow.log_metric:", e)

        # subimos las graficas cada 5 épocas
        if (epoch + 1) % self.plot_every_n_epochs == 0:
            try:
                epochs_range = range(1, len(self.history['loss']) + 1)

                # graficas de loss
                fig, ax = plt.subplots(figsize=(10, 6))
                ax.plot(epochs_range, self.history['loss'], label='Train Loss', linewidth=2)
                ax.plot(epochs_range, self.history['val_loss'], label='Val Loss', linewidth=2)
                ax.set_xlabel('Época')
                ax.set_ylabel('Loss')
                ax.set_title('Evolución del Loss')
                ax.legend()
                ax.grid(True, alpha=0.3)
                loss_img = f'loss_epoch_{epoch+1}.png'
                fig.savefig(loss_img, dpi=100, bbox_inches='tight')
                plt.close(fig)
                mlflow.log_artifact(loss_img, artifact_path="plots")
                os.remove(loss_img)

                # las del acuaracy
                fig, ax = plt.subplots(figsize=(10, 6))
                ax.plot(epochs_range, self.history['accuracy'], label='Train Accuracy', linewidth=2)
                ax.plot(epochs_range, self.history['val_accuracy'], label='Val Accuracy', linewidth=2)
                ax.set_xlabel('Época')
                ax.set_ylabel('Accuracy')
                ax.set_title('Evolución del Accuracy')
                ax.legend()
                ax.grid(True, alpha=0.3)
                acc_img = f'acc_epoch_{epoch+1}.png'
                fig.savefig(acc_img, dpi=100, bbox_inches='tight')
                plt.close(fig)
                mlflow.log_artifact(acc_img, artifact_path="plots")
                os.remove(acc_img)

                print(f" Gráficas (Train/Val) subidas a MLflow (Época {epoch+1})")

            except Exception as e:
                print("Warning al crear/logear plots:", e)

print("Logger de gráficas de MLflow (Loss/Accuracy) creado.")

"""OPTUNA"""

def create_model_from_trial_categorical(trial):
    """Crear modelo con clasificación categórica"""

    # hiperparametros
    unfreeze_layers = trial.suggest_int("unfreeze_layers", 10, 100)
    dropout_rate = trial.suggest_float("dropout", 0.1, 0.5)

    # base preentrenada
    base_model = EfficientNetB2(
        weights='imagenet',
        include_top=False,
        input_shape=(256, 256, 3)
    )

    #congelamos capas
    base_model.trainable = True
    for layer in base_model.layers[:-unfreeze_layers]:
        layer.trainable = False

    # se construye el modelo
    inputs = tf.keras.Input(shape=(256, 256, 3))
    x = base_model(inputs, training=True)
    x = layers.GlobalAveragePooling2D()(x)

    n_dense_layers = trial.suggest_int("n_dense_layers", 1, 3)
    for i in range(n_dense_layers):
        units = trial.suggest_int(f"dense_units_{i}", 64, 512, log=True)

        #orden a seguir
        x = layers.Dense(units, use_bias=False)(x)
        x = layers.BatchNormalization()(x)
        x = layers.Activation('relu')(x)
        x = layers.Dropout(dropout_rate)(x)

    # capa de salida usando softmax
    outputs = layers.Dense(num_classes, activation='softmax')(x)
    model = tf.keras.Model(inputs, outputs)

    # optimizador
    lr = trial.suggest_float("lr", 1e-5, 1e-3, log=True)
    optimizer_name = trial.suggest_categorical("optimizer", ["adam", "rmsprop"])

    if optimizer_name == "adam":
        optimizer = optimizers.Adam(learning_rate=lr)
    else:
        optimizer = optimizers.RMSprop(learning_rate=lr)

    #hacemos la compilacion con categorical cross entropy
    model.compile(
        optimizer=optimizer,
        loss='categorical_crossentropy',
        metrics=['accuracy']
    )

    return model, base_model

"""OBJETIVO DE OPTUNA"""

def objective(trial):

    try:
        with mlflow.start_run(nested=True):
            run_id = mlflow.active_run().info.run_id

            #este es el log de hiperparámetros
            model, base_model = create_model_from_trial_categorical(trial)
            trial_params = trial.params
            mlflow.log_params(trial_params)

            # nuestros callbacks
            checkpoint_path = f"best_model_trial_{run_id}.h5"

            checkpoint_cb = ModelCheckpoint(
                checkpoint_path, monitor='val_loss', verbose=0, save_best_only=True, mode='min'
            )
            earlystop_cb = EarlyStopping(
                monitor='val_loss', mode='min', patience=8, restore_best_weights=True, verbose=0
            )
            lr_scheduler_cb = ReduceLROnPlateau(
                monitor='val_loss', factor=0.2, patience=3, verbose=0, min_lr=1e-6
            )
            # --- Logger de gráficas RE-AÑADIDO ---
            mlflow_logger_cb = MLflowEpochLogger(log_every_n_epochs=1, plot_every_n_epochs=5)


            # entrenamiento
            history = model.fit(
                train_gen,
                validation_data=val_gen,
                epochs=20,
                batch_size=BATCH_SIZE,

                callbacks=[checkpoint_cb, earlystop_cb, lr_scheduler_cb, mlflow_logger_cb],
                verbose=0
            )

            # evaluacion final
            val_loss = min(history.history['val_loss'])


            # hacemos el log del mejor modelo
            if os.path.exists(checkpoint_path):
                mlflow.log_artifact(checkpoint_path, artifact_path="models")

            final_val_loss = val_loss

    except Exception as e:
        print(f"Trial falló: {e}")
        final_val_loss = float('inf')

    finally:
        # limpiamos la sesion de keras para liberar memoria
        tf.keras.backend.clear_session()
        del model
        del base_model
        if 'checkpoint_path' in locals() and os.path.exists(checkpoint_path):
            os.remove(checkpoint_path)

    return float(final_val_loss)

"""EJECUTAMOS OPTUNA"""

try:
    mlflow.set_experiment(EXPERIMENT_NAME)
    print(f" Experimento MLflow establecido: {EXPERIMENT_NAME}")
except Exception as e:
    print("Warning al set_experiment:", e)

print(f"\n🔍 Iniciando búsqueda de hiperparámetros con {N_TRIALS} trials...")
study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=N_TRIALS, show_progress_bar=True)

print("Optimización completada")
print(f"Mejor valor (val_loss): {study.best_value:.4f}")
print("Mejores hiperparámetros:", study.best_params)

"""MODELO FINAL"""

BEST_MODEL_PATH = "best_model_plant_pathology_final.h5"

def build_final_model_categorical(params):

    print("Construyendo modelo final con parámetros:", params)

    # base preentrenada
    base_model = EfficientNetB2(
        weights='imagenet',
        include_top=False,
        input_shape=(256, 256, 3)
    )

    # configuramos capas preentreables
    unfreeze_layers = params.get("unfreeze_layers", 50)
    base_model.trainable = True
    for layer in base_model.layers[:-unfreeze_layers]:
        layer.trainable = False
    print(f"Capas descongeladas: {unfreeze_layers}")

    # construimos el modelo
    inputs = tf.keras.Input(shape=(256, 256, 3))
    x = base_model(inputs, training=True)
    x = layers.GlobalAveragePooling2D()(x)


    n_dense_layers = params.get("n_dense_layers", 2)
    dropout_rate = params.get("dropout", 0.3)
    print(f"Capas densas: {n_dense_layers}, Dropout: {dropout_rate}")

    for i in range(n_dense_layers):
        units = params.get(f"dense_units_{i}", 256)
        print(f"Capa densa {i} con {int(units)} unidades")


        x = layers.Dense(int(units), use_bias=False)(x)
        x = layers.BatchNormalization()(x)
        x = layers.Activation('relu')(x)
        x = layers.Dropout(float(dropout_rate))(x)


    #nuestra capa de salida sera con softmax
    outputs = layers.Dense(num_classes, activation='softmax')(x)
    model = tf.keras.Model(inputs, outputs)

    # optimizador
    lr = params.get("lr", 1e-4)
    optimizer_name = params.get("optimizer", "adam")
    print(f"Optimizador: {optimizer_name}, LR: {float(lr)}")

    if optimizer_name == "adam":
        optimizer = optimizers.Adam(learning_rate=float(lr))
    else:
        optimizer = optimizers.RMSprop(learning_rate=float(lr))

    # compilamos usando categorical cross entropy
    model.compile(
        optimizer=optimizer,
        loss='categorical_crossentropy',
        metrics=['accuracy']
    )

    return model, base_model

print("\n Construyendo modelo final con clasificación categórica...")
final_model, final_base_model = build_final_model_categorical(study.best_params)
final_model.summary()

"""ENTRENAMIENTO FINAL"""

try:
    with mlflow.start_run(run_name="final_training_categorical_with_plots") as run:
        print("Iniciando run de MLflow para entrenamiento final.")

        # callbacs para entrenamiento final
        checkpoint_cb = ModelCheckpoint(
            BEST_MODEL_PATH, monitor='val_loss', verbose=1, save_best_only=True, mode='min'
        )
        earlystop_cb = EarlyStopping(
            monitor='val_loss', mode='min', patience=10, restore_best_weights=True, verbose=1
        )
        final_lr_scheduler_cb = ReduceLROnPlateau(
            monitor='val_loss', factor=0.2, patience=3, verbose=1, min_lr=1e-7
        )

        mlflow_logger_cb = MLflowEpochLogger(log_every_n_epochs=1, plot_every_n_epochs=5)

        # hacemos el log de los datos finales
        mlflow.log_params(study.best_params)
        mlflow.log_param("final_epochs", FINAL_EPOCHS)
        mlflow.log_param("batch_size", BATCH_SIZE)
        mlflow.log_param("img_size", IMG_SIZE)
        mlflow.log_param("num_classes", num_classes)
        mlflow.log_param("classes", str(clases))

        print("\n Iniciando entrenamiento final...")
        history = final_model.fit(
            train_gen,
            validation_data=val_gen,
            epochs=FINAL_EPOCHS,
            batch_size=BATCH_SIZE,

            callbacks=[checkpoint_cb, earlystop_cb, final_lr_scheduler_cb, mlflow_logger_cb],
            verbose=1
        )



        print("\nCargando el mejor modelo guardado para evaluación final...")
        if os.path.exists(BEST_MODEL_PATH):
            final_model = tf.keras.models.load_model(BEST_MODEL_PATH)
        else:
            print("Warning: No se encontró .h5, usando el modelo en memoria (puede no ser el mejor).")

        #evaluamos el test
        print("\n Evaluando modelo final en conjunto de test...")
        test_results = final_model.evaluate(test_gen, verbose=1)
        print(f" Resultados en Test:")
        print(f"   - Loss: {test_results[0]:.4f}")
        print(f"   - Accuracy: {test_results[1]:.4f}")

        #subimos las metricas finales
        mlflow.log_metric("final_test_loss", float(test_results[0]))
        mlflow.log_metric("final_test_accuracy", float(test_results[1]))

        # subimos el modelo final
        print("Subiendo modelo final a MLflow...")
        mlflow.keras.log_model(final_model, artifact_path="final_keras_model")
        mlflow.log_artifact(BEST_MODEL_PATH, artifact_path="models")

        print(f"\n ¡ENTRENAMIENTO COMPLETADO!")
        print(f" Mejor modelo guardado en: {BEST_MODEL_PATH}")
        print(f" Puedes ver los resultados en: {tracking_uri}")

except Exception as e:
    print(f"Error durante el entrenamiento final: {e}")
    mlflow.end_run("FAILED")